export const USER_COMMENT_REQUEST="USER_COMMENT_REQUEST";
export const USER_COMMENT_SUCCESSFUL="USER_COMMENT_SUCCESSFUL";
export const USER_COMMENT_FAILED="USER_COMMENT_FAILED";
export const USER_COMMENT_RESET="USER_COMMENT_RESET";

export const USER_EDIT_COMMENT_REQUEST="USER_EDIT_COMMENT_REQUEST";
export const USER_EDIT_COMMENT_SUCCESSFUL="USER_EDIT_COMMENT_SUCCESSFUL";
export const USER_EDIT_COMMENT_FAILED="USER_EDIT_COMMENT_FAILED";
export const USER_EDIT_COMMENT_RESET="USER_EDIT_COMMENT_RESET";

export const USER_DELETE_COMMENT_REQUEST="USER_DELETE_COMMENT_REQUEST";
export const USER_DELETE_COMMENT_SUCCESSFUL="USER_DELETE_COMMENT_SUCCESSFUL";
export const USER_DELETE_COMMENT_FAILED="USER_DELETE_COMMENT_FAILED";

export const USER_COMMENT_LIST_REQUEST="USER_COMMENT_LIST_REQUEST";
export const USER_COMMENT_LIST_SUCCESSFUL="USER_COMMENT_LIST_SUCCESSFUL";
export const USER_COMMENT_LIST_FAILED="USER_COMMENT_LIST_FAILED";

export const USER_FILTER_COMMENT_BY_STAR_REQUEST="USER_FILTER_COMMENT_BY_STAR_REQUEST";
export const USER_FILTER_COMMENT_BY_STAR_SUCCESSFUL="USER_FILTER_COMMENT_BY_STAR_SUCCESSFUL";
export const USER_FILTER_COMMENT_BY_STAR_FAILED="USER_FILTER_COMMENT_BY_STAR_FAILED";
export const USER_FILTER_COMMENT_BY_STAR_RESET="USER_FILTER_COMMENT_BY_STAR_RESET";

export const USER_SORT_COMMENT_REQUEST="USER_SORT_COMMENT_REQUEST";
export const USER_SORT_COMMENT_SUCCESSFUL="USER_SORT_COMMENT_SUCCESSFUL";
export const USER_SORT_COMMENT_FAILED="USER_SORT_COMMENT_FAILED";
export const USER_SORT_COMMENT_RESET="USER_SORT_COMMENT_RESET";