export const DRINK_LIST_REQUEST = 'DRINK_LIST_REQUEST';
export const DRINK_LIST_SUCCESSFUL = 'DRINK_LIST_SUCCESSFUL';
export const DRINK_LIST_FAILED = 'DRINK_LIST_FAILED';

export const DRINK_DETAIL_REQUEST = 'DRINK_DETAIL_REQUEST';
export const DRINK_DETAIL_SUCCESSFUL = 'DRINK_DETAIL_SUCCESSFUL';
export const DRINK_DETAIL_FAILED = 'DRINK_DETAIL_FAILED';

export const SHOW_RELATED_DRINK_REQUEST ='SHOW_RELATED_DRINK_REQUEST';
export const SHOW_RELATED_DRINK_SUCCESSFUL ='SHOW_RELATED_DRINK_SUCCESSFUL';
export const SHOW_RELATED_DRINK_FAILED ='SHOW_RELATED_DRINK_FAILED';

export const DRINK_SEARCH_REQUEST ='DRINK_SEARCH_REQUEST';
export const DRINK_SEARCH_SUCCESSFUL ='DRINK_SEARCH_SUCCESSFUL';
export const DRINK_SEARCH_FAILED ='DRINK_SEARCH_FAILED';

export const DRINK_FILTER_BY_STAR_REQUEST = 'DRINK_FILTER_BY_STAR_REQUEST';
export const DRINK_FILTER_BY_STAR_SUCCESSFUL = 'DRINK_FILTER_BY_STAR_SUCCESSFUL';
export const DRINK_FILTER_BY_STAR_FAILED = 'DRINK_FILTER_BY_STAR_FAILED';

export const DRINK_FILTER_BY_PRICE_REQUEST = 'DRINK_FILTER_BY_PRICE_REQUEST';
export const DRINK_FILTER_BY_PRICE_SUCCESSFUL = 'DRINK_FILTER_BY_PRICE_SUCCESSFUL';
export const DRINK_FILTER_BY_PRICE_FAILED = 'DRINK_FILTER_BY_PRICE_FAILED';