export const DRINK_LIST_REQUEST = 'DRINK_LIST_REQUEST';
export const DRINK_LIST_SUCCESSFUL = 'DRINK_LIST_SUCCESSFUL';
export const DRINK_LIST_FAILED = 'DRINK_LIST_FAILED';

export const DRINK_DETAIL_REQUEST = 'DRINK_DETAIL_REQUEST';
export const DRINK_DETAIL_SUCCESSFUL = 'DRINK_DETAIL_SUCCESSFUL';
export const DRINK_DETAIL_FAILED = 'DRINK_DETAIL_FAILED';

export const SHOW_RELATED_DRINK_REQUEST ='SHOW_RELATED_DRINK_REQUEST';
export const SHOW_RELATED_DRINK_SUCCESSFUL ='SHOW_RELATED_DRINK_SUCCESSFUL';
export const SHOW_RELATED_DRINK_FAILED ='SHOW_RELATED_DRINK_FAILED';

export const DRINK_SEARCH_REQUEST ='DRINK_SEARCH_REQUEST';
export const DRINK_SEARCH_SUCCESSFUL ='DRINK_SEARCH_SUCCESSFUL';
export const DRINK_SEARCH_FAILED ='DRINK_SEARCH_FAILED';

export const DRINK_FILTER_BY_STAR_REQUEST = 'DRINK_FILTER_BY_STAR_REQUEST';
export const DRINK_FILTER_BY_STAR_SUCCESSFUL = 'DRINK_FILTER_BY_STAR_SUCCESSFUL';
export const DRINK_FILTER_BY_STAR_FAILED = 'DRINK_FILTER_BY_STAR_FAILED';

export const DRINK_FILTER_BY_PRICE_REQUEST = 'DRINK_FILTER_BY_PRICE_REQUEST';
export const DRINK_FILTER_BY_PRICE_SUCCESSFUL = 'DRINK_FILTER_BY_PRICE_SUCCESSFUL';
export const DRINK_FILTER_BY_PRICE_FAILED = 'DRINK_FILTER_BY_PRICE_FAILED';

export const DRINK_RATING_REQUEST = "DRINK_RATING_REQUEST";
export const DRINK_RATING_SUCCESSFUL = "DRINK_RATING_SUCCESSFUL";
export const DRINK_RATING_FAILED = "DRINK_RATING_FAILED";

export const DRINK_ADD_TAG_REQUEST = "DRINK_ADD_TAG_REQUEST";
export const DRINK_ADD_TAG_SUCCESSFUL = "DRINK_ADD_TAG_SUCCESSFUL";
export const DRINK_ADD_TAG_FAILED = "DRINK_ADD_TAG_FAILED";

export const DRINK_REMOVE_TAG_REQUEST = "DRINK_REMOVE_TAG_REQUEST";
export const DRINK_REMOVE_TAG_SUCCESSFUL = "DRINK_REMOVE_TAG_SUCCESSFUL";
export const DRINK_REMOVE_TAG_FAILED = "DRINK_REMOVE_TAG_FAILED";

export const DRINK_ADD_REQUEST = 'DRINK_ADD_REQUEST';
export const DRINK_ADD_SUCCESSFUL = 'DRINK_ADD_SUCCESSFUL';
export const DRINK_ADD_FAILED = 'DRINK_ADD_FAILED';

export const DRINK_UPDATE_REQUEST = 'DRINK_UPDATE_REQUEST';
export const DRINK_UPDATE_SUCCESSFUL = 'DRINK_UPDATE_SUCCESSFUL';
export const DRINK_UPDATE_FAILED = 'DRINK_UPDATE_FAILED';
export const DRINK_UPDATE_RESET = 'DRINK_UPDATE_RESET';

export const DRINK_DELETE_REQUEST = 'DRINK_DELETE_REQUEST';
export const DRINK_DELETE_SUCCESSFUL = 'DRINK_DELETE_SUCCESSFUL';
export const DRINK_DELETE_FAILED = 'DRINK_DELETE_FAILED';

export const DRINK_ADD_FEATURE_REQUEST = 'DRINK_ADD_FEATURE_REQUEST';
export const DRINK_ADD_FEATURE_SUCCESSFUL = 'DRINK_ADD_FEATURE_SUCCESSFUL';
export const DRINK_ADD_FEATURE_FAILED = 'DRINK_ADD_FEATURE_FAILED';

export const DRINK_REMOVE_FEATURE_REQUEST = 'DRINK_REMOVE_FEATURE_REQUEST';
export const DRINK_REMOVE_FEATURE_SUCCESSFUL = 'DRINK_REMOVE_FEATURE_SUCCESSFUL';
export const DRINK_REMOVE_FEATURE_FAILED = 'DRINK_REMOVE_FEATURE_FAILED';

export const DRINK_REMOVE_ALL_FEATURE_REQUEST = 'DRINK_REMOVE_ALL_FEATURE_REQUEST';
export const DRINK_REMOVE_ALL_FEATURE_SUCCESSFUL = 'DRINK_REMOVE_ALL_FEATURE_SUCCESSFUL';
export const DRINK_REMOVE_ALL_FEATURE_FAILED = 'DRINK_REMOVE_ALL_FEATURE_FAILED';