export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESSFUL = 'ORDER_CREATE_SUCCESSFUL';
export const ORDER_CREATE_FAILED = 'ORDER_CREATE_FAILED';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESSFUL = 'ORDER_PAY_SUCCESSFUL';
export const ORDER_PAY_FAILED = 'ORDER_PAY_FAILED';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const ORDER_DETAIL_SUCCESSFUL = 'ORDER_DETAIL_SUCCESSFUL';
export const ORDER_DETAIL_FAILED = 'ORDER_DETAIL_FAILED';
export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST';

export const ORDER_LIST_SUCCESSFUL = 'ORDER_LIST_SUCCESSFUL';
export const ORDER_LIST_FAILED = 'ORDER_LIST_FAILED';
export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';

export const ORDER_TOTAL_SUCCESSFUL = 'ORDER_TOTAL_SUCCESSFUL';
export const ORDER_TOTAL_FAILED = 'ORDER_TOTAL_FAILED';
export const ORDER_TOTAL_REQUEST = 'ORDER_TOTAL_REQUEST';
export const ORDER_TOTAL_RESET = 'ORDER_TOTAL_RESET';
