export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESSFUL = 'ORDER_CREATE_SUCCESSFUL';
export const ORDER_CREATE_FAILED = 'ORDER_CREATE_FAILED';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESSFUL = 'ORDER_PAY_SUCCESSFUL';
export const ORDER_PAY_FAILED = 'ORDER_PAY_FAILED';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const ORDER_DETAIL_SUCCESSFUL = 'ORDER_DETAIL_SUCCESSFUL';
export const ORDER_DETAIL_FAILED = 'ORDER_DETAIL_FAILED';
export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST';

export const ORDER_LIST_SUCCESSFUL = 'ORDER_LIST_SUCCESSFUL';
export const ORDER_LIST_FAILED = 'ORDER_LIST_FAILED';
export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';

export const ORDER_TOTAL_SUCCESSFUL = 'ORDER_TOTAL_SUCCESSFUL';
export const ORDER_TOTAL_FAILED = 'ORDER_TOTAL_FAILED';
export const ORDER_TOTAL_REQUEST = 'ORDER_TOTAL_REQUEST';
export const ORDER_TOTAL_RESET = 'ORDER_TOTAL_RESET';

export const ORDER_TOTAL_OF_ALL_USERS_SUCCESSFUL = 'ORDER_TOTAL_OF_ALL_USERS_SUCCESSFUL';
export const ORDER_TOTAL_OF_ALL_USERS_FAILED = 'ORDER_TOTAL_OF_ALL_USERS_FAILED';
export const ORDER_TOTAL_OF_ALL_USERS_REQUEST = 'ORDER_TOTAL_OF_ALL_USERS_REQUEST';
export const OORDER_TOTAL_OF_ALL_USERS_RESET = 'OORDER_TOTAL_OF_ALL_USERS_RESET';

export const ALL_ORDER_LIST_SUCCESSFUL = 'ALL_ORDER_LIST_SUCCESSFUL';
export const ALL_ORDER_LIST_FAILED = 'ALL_ORDER_LIST_FAILED';
export const ALL_ORDER_LIST_REQUEST = 'ALL_ORDER_LIST_REQUEST';

export const ORDER_FILTER_BY_DATE_REQUEST="ORDER_FILTER_BY_DATE_REQUEST";
export const ORDER_FILTER_BY_DATE_SUCCESSFUL="ORDER_FILTER_BY_DATE_SUCCESSFUL";
export const ORDER_FILTER_BY_DATE_FAILED="ORDER_FILTER_BY_DATE_FAILED";

export const ORDER_DATE_REQUEST="ORDER_DATE_REQUEST";
export const ORDER_DATE_SUCCESSFUL="ORDER_DATE_SUCCESSFUL";
export const ORDER_DATE_FAILED="ORDER_DATE_FAILED";

export const ORDER_MONTH_REQUEST="ORDER_MONTH_REQUEST";
export const ORDER_MONTH_SUCCESSFUL="ORDER_MONTH_SUCCESSFUL";
export const ORDER_MONTH_FAILED="ORDER_MONTH_FAILED";

export const ORDER_YEAR_REQUEST="ORDER_YEAR_REQUEST";
export const ORDER_YEAR_SUCCESSFUL="ORDER_YEAR_SUCCESSFUL";
export const ORDER_YEAR_FAILED="ORDER_YEAR_FAILED";

export const ORDER_ISPAID_REQUEST="ORDER_ISPAID_REQUEST";
export const ORDER_ISPAID_SUCCESSFUL="ORDER_ISPAID_SUCCESSFUL";
export const ORDER_ISPAID_FAILED="ORDER_ISPAID_FAILED";

// export const ORDER_ISNOTPAID_REQUEST="ORDER_ISNOTPAID_REQUEST";
// export const ORDER_ISNOTPAID_SUCCESSFUL="ORDER_ISNOTPAID_SUCCESSFUL";
// export const ORDER_ISNOTPAID_FAILED="ORDER_ISNOTPAID_FAILED";

export const ORDER_ISDELIVERED_REQUEST="ORDER_ISDELIVERED_REQUEST";
export const ORDER_ISDELIVERED_SUCCESSFUL="ORDER_ISDELIVERED_SUCCESSFUL";
export const ORDER_ISDELIVERED_FAILED="ORDER_ISDELIVERED_FAILED";

// export const ORDER_ISNOTDELIVERED_REQUEST="ORDER_ISNOTDELIVERED_REQUEST";
// export const ORDER_ISNOTDELIVERED_SUCCESSFUL="ORDER_ISNOTDELIVERED_SUCCESSFUL";
// export const ORDER_ISNOTDELIVERED_FAILED="ORDER_ISNOTDELIVERED_FAILED";

export const ORDER_MAX_TOTAL_REQUEST="ORDER_MAX_TOTAL_REQUEST";
export const ORDER_MAX_TOTAL_SUCCESSFUL="ORDER_MAX_TOTAL_SUCCESSFUL";
export const ORDER_MAX_TOTAL_FAILED="ORDER_MAX_TOTAL_FAILED";

export const ORDER_SORT_BY_DATE_REQUEST="ORDER_SORT_BY_DATE_REQUEST";
export const ORDER_SORT_BY_DATE_SUCCESSFUL="ORDER_SORT_BY_DATE_SUCCESSFUL";
export const ORDER_SORT_BY_DATE_FAILED="ORDER_SORT_BY_DATE_FAILED";

export const ORDER_SORT_BY_TOTAL_REQUEST="ORDER_SORT_BY_TOTAL_REQUEST";
export const ORDER_SORT_BY_TOTAL_SUCCESSFUL="ORDER_SORT_BY_TOTAL_SUCCESSFUL";
export const ORDER_SORT_BY_TOTAL_FAILED="ORDER_SORT_BY_TOTAL_FAILED";

export const MOST_ORDERED_DRINK_REQUEST="MOST_ORDERED_DRINK_REQUEST";
export const MOST_ORDERED_DRINK_SUCCESSFUL="MOST_ORDERED_DRINK__SUCCESSFUL";
export const MOST_ORDERED_DRINK_FAILED="MOST_ORDERED_DRINK__FAILED";

export const LEAST_ORDERED_DRINK_REQUEST="LEAST_ORDERED_DRINK_REQUEST";
export const LEAST_ORDERED_DRINK_SUCCESSFUL="LEAST_ORDERED_DRINK_SUCCESSFUL";
export const LEAST_ORDERED_DRINK_FAILED="LEAST_ORDERED_DRINK_FAILED";



