export const USER_SIGN_UP_REQUEST = 'USER_SIGN_UP_REQUEST';
export const USER_SIGN_UP_SUCCESSFUL = 'USER_SIGN_UP_SUCCESSFUL';
export const USER_SIGN_UP_FAILED = 'USER_SIGN_UP_FAILED';



export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESSFUL = 'USER_SIGNIN_SUCCESSFUL';
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED';
export const USER_SIGNOUT = 'USER_SIGNOUT';
export const CLEAR_ALL = "CLEAR_ALL";


export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESSFUL = 'USER_LIST_SUCCESSFUL';
export const USER_LIST_FAILED = 'USER_LIST_FAILED';

export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST';
export const USER_DETAIL_SUCCESSFUL= 'USER_DETAIL_SUCCESSFUL';
export const USER_DETAIL_FAILED = 'USER_DETAIL_FAILED';

export const USER_UPDATE_PROFILE_REQUEST="USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESSFUL="USER_UPDATE_PROFILE_SUCCESSFUL";
export const USER_UPDATE_PROFILE_FAILED="USER_UPDATE_PROFILE_FAILED";
export const USER_UPDATE_PROFILE_RESET="USER_UPDATE_PROFILE_RESET";

export const USERS_SEARCH_REQUEST="USERS_SEARCH_REQUEST";
export const USERS_SEARCH_SUCCESSFUL="USERS_SEARCH_SUCCESSFUL";
export const USERS_SEARCH_FAILED="USERS_SEARCH_FAILED";

export const MOST_SPENDING_USER_REQUEST = 'MOST_SPENDING_USER_REQUEST';
export const MOST_SPENDING_USER_SUCCESSFUL = 'MOST_SPENDING_USER_SUCCESSFUL';
export const MOST_SPENDING_USER_FAILED = 'MOST_SPENDING_USER_FAILED';

// export const LEAST_SPENDING_USER_REQUEST = 'LEAST_SPENDING_USER_REQUEST';
// export const LEAST_SPENDING_USER_SUCCESSFUL = 'LEAST_SPENDING_USER_SUCCESSFUL';
// export const LEAST_SPENDING_USER_FAILED = 'LEAST_SPENDING_USER_FAILED';

export const USER_SORT_BY_SPENDING_REQUEST = 'USER_SORT_BY_SPENDING_REQUEST';
export const USER_SORT_BY_SPENDING_SUCCESSFUL = 'USER_SORT_BY_SPENDING_SUCCESSFUL';
export const USER_SORT_BY_SPENDING_FAILED = 'USER_SORT_BY_SPENDING_FAILED';

export const USER_SORT_BY_ORDER_REQUEST = 'USER_SORT_BY_ORDER_REQUEST';
export const USER_SORT_BY_ORDER_SUCCESSFUL = 'USER_SORT_BY_ORDER_SUCCESSFUL';
export const USER_SORT_BY_ORDER_FAILED = 'USER_SORT_BY_ORDER_FAILED';

export const USER_SORT_BY_NAME_REQUEST = 'USER_SORT_BY_NAME_REQUEST';
export const USER_SORT_BY_NAME_SUCCESSFUL = 'USER_SORT_BY_NAME_SUCCESSFUL';
export const USER_SORT_BY_NAME_FAILED = 'USER_SORT_BY_NAME_FAILED';

export const USER_SORT_BY_DATE_REQUEST = 'USER_SORT_BY_DATE_REQUEST';
export const USER_SORT_BY_DATE_SUCCESSFUL = 'USER_SORT_BY_DATE_SUCCESSFUL';
export const USER_SORT_BY_DATE_FAILED = 'USER_SORT_BY_DATE_FAILED';



